version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - jenkins_network

  # Optional: Add a MySQL service for testing if needed
  mysql:
    image: mysql:8.0
    container_name: jenkins_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jenkins
      MYSQL_USER: jenkins
      MYSQL_PASSWORD: jenkins
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jenkins_network

volumes:
  jenkins_home:
    driver: local
  mysql_data:
    driver: local

networks:
  jenkins_network:
    driver: bridge
